"""ANYfem -- a shell and beam finite element application.

Geometry modelling, mapped meshing, loads and boundary conditions, solving and
postprocessing, built on ``anysolver`` for the analysis and ``anytk3d`` for
the viewport.

Modelling is bottom-up and point-driven::

    from anyfem import Project, steel

    project = Project(name="plate")
    project.add_material(steel("S355", thickness=0.010))
    project.add_plate_section("deck", thickness=0.010, material="S355")

    points = project.geometry.add_points(
        [(0, 0, 0), (2, 0, 0), (2, 1, 0), (0, 1, 0)]
    )
    face = project.geometry.add_plate(points)
    project.assign_plate(face, "deck")

Everything in this package works headless; the 3D viewport lives in
``anyfem.ui`` and is the only part that needs Tk.
"""

from .geometry import (
    ConstructionMode,
    ConstructionResult,
    ConstructionTask,
    CoordinateConstruction,
    Edge,
    EntityRef,
    Face,
    GeometryError,
    GeometryModel,
    GeometrySnapData,
    OrientedEdge,
    SnapCandidate,
    SnapEngine,
    SnapKind,
    SnapPoint,
    SnapResult,
    SnapSegment,
    Vertex,
    geometry_snap_data,
)
from .mesh import Mesh, MeshError, Seeding, SeedingConflict, generate_mesh, solve_seeding
from .model import (
    AnalysisDefinition,
    ArtifactRef,
    BeamSection,
    CoordinateSystem,
    LoadCase,
    Material,
    MeshEntityRef,
    OutputRequest,
    JobRecord,
    JobStatus,
    PlateSection,
    Project,
    ProjectError,
    Region,
    RegionRegistry,
    RegionRef,
    ResultQuantityDescriptor,
    SectionAssignment,
    Support,
    fixed,
    pinned,
    antisymmetry,
    simply_supported,
    symmetry,
    steel,
    support,
    UnitProfile,
    Workplane,
    WorkplaneError,
    WorkplaneFrame,
)
from .document import DocumentRevision, DocumentSession, ProjectSnapshot
from .jobs import JobEvent, JobManager, JobRequest
from .scripting import (
    ScriptCancelled,
    ScriptCancellationToken,
    ScriptCommit,
    ScriptConflictError,
    ScriptError,
    ScriptExecutionError,
    ScriptResult,
    ScriptRunner,
    ScriptTask,
    ScriptValidationError,
)
from .post import (
    BucklingSolution,
    ImpactSolution,
    LinearBatchSolution,
    LinearSolution,
    ModalSolution,
    NonlinearSolution,
    ShapeView,
    TransientSolution,
)
from .solve import (
    BuiltModel,
    build_fe_model,
    eigenmode_imperfection,
    preflight,
    solve_arc_length,
    recovery_policy,
    resource_policy,
    solve_buckling,
    solve_capacity,
    solve_impact,
    solve_linear_static,
    solve_linear_static_many,
    solve_modal,
    solve_nonlinear_static,
    solve_transient,
)

__version__ = "0.0.1"

__all__ = [
    "BeamSection",
    "AnalysisDefinition",
    "ArtifactRef",
    "BucklingSolution",
    "BuiltModel",
    "CoordinateSystem",
    "ConstructionMode",
    "ConstructionResult",
    "ConstructionTask",
    "CoordinateConstruction",
    "DocumentRevision",
    "DocumentSession",
    "Edge",
    "EntityRef",
    "Face",
    "GeometryError",
    "GeometryModel",
    "GeometrySnapData",
    "ImpactSolution",
    "LinearBatchSolution",
    "LinearSolution",
    "LoadCase",
    "Material",
    "MeshEntityRef",
    "Mesh",
    "MeshError",
    "ModalSolution",
    "NonlinearSolution",
    "OrientedEdge",
    "OutputRequest",
    "SnapCandidate",
    "SnapEngine",
    "SnapKind",
    "SnapPoint",
    "SnapResult",
    "SnapSegment",
    "PlateSection",
    "Project",
    "ProjectSnapshot",
    "ProjectError",
    "Seeding",
    "SeedingConflict",
    "ShapeView",
    "ScriptCancelled",
    "ScriptCancellationToken",
    "ScriptCommit",
    "ScriptConflictError",
    "ScriptError",
    "ScriptExecutionError",
    "ScriptResult",
    "ScriptRunner",
    "ScriptTask",
    "ScriptValidationError",
    "Support",
    "JobRecord",
    "JobEvent",
    "JobManager",
    "JobRequest",
    "JobStatus",
    "Region",
    "RegionRegistry",
    "RegionRef",
    "ResultQuantityDescriptor",
    "SectionAssignment",
    "TransientSolution",
    "UnitProfile",
    "Workplane",
    "WorkplaneError",
    "WorkplaneFrame",
    "Vertex",
    "__version__",
    "build_fe_model",
    "eigenmode_imperfection",
    "fixed",
    "geometry_snap_data",
    "generate_mesh",
    "pinned",
    "preflight",
    "simply_supported",
    "solve_arc_length",
    "recovery_policy",
    "resource_policy",
    "solve_buckling",
    "solve_capacity",
    "solve_impact",
    "solve_linear_static",
    "solve_linear_static_many",
    "solve_modal",
    "solve_nonlinear_static",
    "solve_seeding",
    "solve_transient",
    "steel",
    "antisymmetry",
    "support",
    "symmetry",
]
