"""Model layer: materials, sections, supports, loads, and the project."""

from .attributes import (
    DOF_NAMES,
    Combination,
    LineLoad,
    LoadCase,
    Mass,
    PointLoad,
    Pressure,
    Support,
    SurfaceTraction,
    antisymmetry,
    fixed,
    pinned,
    prescribed,
    simply_supported,
    support,
    symmetry,
)
from .collision import (
    Collision,
    CollisionTiming,
    auto_timing,
    fracture,
    impact_damage,
)
from .imperfections import Imperfection, member_bow, plate_mode
from .materials import Material, steel
from .project import Project, ProjectError
from .sections import (
    PROFILES,
    BeamSection,
    PlateSection,
    SectionAssignment,
    rectangular_bar,
)
from .coordinates import CoordinateSystem, CoordinateSystemError, GLOBAL_COORDINATES
from .records import (
    AnalysisDefinition,
    ArtifactRef,
    ArtifactState,
    JobRecord,
    JobStatus,
    MeshRecord,
    OutputRequest,
    ResultQuantityDescriptor,
)
from .regions import (
    BooleanRegion,
    ElementFaceRef,
    GeometryGroupRef,
    ManualRegion,
    MeshEntityRef,
    QueryClause,
    QueryGroup,
    QueryRegion,
    Region,
    RegionDomain,
    RegionError,
    RegionRegistry,
    RegionRef,
    RegionStatus,
)
from .units import UNIT_PROFILES, UnitError, UnitProfile, unit_profile
from .workplanes import Workplane, WorkplaneError, WorkplaneFrame

__all__ = [
    "BeamSection",
    "AnalysisDefinition",
    "ArtifactRef",
    "ArtifactState",
    "BooleanRegion",
    "Collision",
    "CollisionTiming",
    "Combination",
    "CoordinateSystem",
    "CoordinateSystemError",
    "DOF_NAMES",
    "Imperfection",
    "ElementFaceRef",
    "GeometryGroupRef",
    "GLOBAL_COORDINATES",
    "JobRecord",
    "JobStatus",
    "LineLoad",
    "LoadCase",
    "Mass",
    "ManualRegion",
    "Material",
    "MeshEntityRef",
    "MeshRecord",
    "OutputRequest",
    "PROFILES",
    "PlateSection",
    "PointLoad",
    "Pressure",
    "Project",
    "ProjectError",
    "QueryClause",
    "QueryGroup",
    "QueryRegion",
    "Region",
    "RegionDomain",
    "RegionError",
    "RegionRegistry",
    "RegionRef",
    "RegionStatus",
    "ResultQuantityDescriptor",
    "SectionAssignment",
    "Support",
    "SurfaceTraction",
    "UNIT_PROFILES",
    "UnitError",
    "UnitProfile",
    "Workplane",
    "WorkplaneError",
    "WorkplaneFrame",
    "antisymmetry",
    "auto_timing",
    "fixed",
    "fracture",
    "impact_damage",
    "member_bow",
    "pinned",
    "plate_mode",
    "prescribed",
    "rectangular_bar",
    "simply_supported",
    "steel",
    "support",
    "symmetry",
    "unit_profile",
]
