"""Postprocessing: results addressed by geometry."""

from .extract import (
    Envelope,
    PathResult,
    Probe,
    along_line,
    envelope,
    nodes_to_elements,
    probe,
)
from .history import Series, has_history, history_series
from .fields import (
    DISPLACEMENT_FIELDS,
    STRESS_FIELDS,
    Field,
    available_fields,
    evaluate_field,
    field_unit,
)
from .report import (
    ResultReport,
    ResultReportContext,
    ResultReportError,
    build_result_report,
    field_to_csv,
    path_to_csv,
    report_markdown,
    result_report_context,
    result_report_html,
    result_report_markdown,
    write_csv,
    write_report,
    write_result_report,
)
from .results import (
    BucklingSolution,
    ImpactSolution,
    LinearBatchSolution,
    LinearSolution,
    ModalSolution,
    MultiShapeSolution,
    NonlinearSolution,
    ShapeView,
    TransientSolution,
)

__all__ = [
    "Series",
    "has_history",
    "history_series",
    "BucklingSolution",
    "DISPLACEMENT_FIELDS",
    "Envelope",
    "Field",
    "ImpactSolution",
    "LinearBatchSolution",
    "LinearSolution",
    "ModalSolution",
    "MultiShapeSolution",
    "NonlinearSolution",
    "PathResult",
    "Probe",
    "ResultReport",
    "ResultReportContext",
    "ResultReportError",
    "STRESS_FIELDS",
    "ShapeView",
    "TransientSolution",
    "along_line",
    "available_fields",
    "build_result_report",
    "envelope",
    "evaluate_field",
    "field_to_csv",
    "field_unit",
    "nodes_to_elements",
    "path_to_csv",
    "probe",
    "report_markdown",
    "result_report_context",
    "result_report_html",
    "result_report_markdown",
    "write_csv",
    "write_report",
    "write_result_report",
]
