"""Writing results out: a Markdown summary and CSV field dumps.

Both go through the headless layer, so a report is scriptable and does not
need the application open.  The report states what it was asked for and what
the solver reported; it does not editorialise about whether the answer is
acceptable, which is the engineer's call.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, List, Sequence


from ..geometry.entities import EntityRef
from .extract import PathResult, probe
from .fields import evaluate_field, field_unit

__all__ = [
    "field_to_csv",
    "path_to_csv",
    "report_markdown",
    "write_csv",
    "write_report",
]

_DEFAULT_FIELDS: tuple[str, ...] = ("magnitude", "uz", "von_mises")


def report_markdown(
    solution,
    *,
    fields: Sequence[str] = _DEFAULT_FIELDS,
    per_plate: bool = True,
) -> str:
    """A Markdown summary of one result."""

    built = solution.built
    project = built.project
    mesh = built.mesh
    shape = _first_shape(solution)

    lines: List[str] = [
        f"# {project.name}",
        "",
        f"- analysis: {getattr(shape, 'label', 'result')}",
        f"- status: {getattr(solution, 'status', 'ok')}",
        f"- nodes: {mesh.num_nodes}",
        f"- shell elements: {len(mesh.quads)}",
        f"- beam elements: {len(mesh.beams)}",
        f"- plates: {len(project.geometry.faces)}",
        f"- lines: {len(project.geometry.edges)}",
    ]
    if built.combination:
        lines.append(f"- load combination: {built.combination}")
    elif built.load_case is not None:
        lines.append(f"- load case: {built.load_case.name}")
    if project.imperfections:
        lines.append(f"- imperfections: {len(project.imperfections)}")

    lines += ["", "## Summary", "", solution.summary()]

    shapes = getattr(solution, "shapes", None)
    if shapes:
        lines += ["", "## Shapes", "", "| shape | value |", "| --- | --- |"]
        for item in shapes:
            lines.append(f"| {item.label} | {item.value:.6g} |")

    lines += ["", "## Extremes", "", "| field | unit | min | max | peak |", "| --- | --- | --- | --- | --- |"]
    for name in fields:
        try:
            evaluated = evaluate_field(shape, name)
        except (ValueError, KeyError):
            continue
        if not len(evaluated):
            continue
        low, high = evaluated.range()
        _key, peak = evaluated.extreme()
        lines.append(
            f"| {name} | {evaluated.unit or '-'} | {low:.6g} | {high:.6g} | "
            f"{peak:.6g} |"
        )

    if per_plate and project.geometry.faces:
        lines += ["", "## Per plate", "", "| plate | section | max |uz| [m] | peak von Mises [MPa] |", "| --- | --- | --- | --- |"]
        for face_id in sorted(project.geometry.faces):
            ref = EntityRef("face", face_id)
            if not mesh.nodes_on(ref):
                continue
            section = project.face_sections.get(face_id, "-")
            reading = probe(shape, ref)
            vertical = abs(reading.displacement.get("uz", 0.0))
            von_mises = reading.stresses.get("von_mises")
            stress_text = "-" if von_mises is None else f"{von_mises / 1e6:.4g}"
            lines.append(
                f"| {face_id} | {section} | {vertical:.6g} | {stress_text} |"
            )

    lines += [
        "",
        "---",
        "",
        "Generated by ANYfem. Numbers are as reported by the solver; whether "
        "they are acceptable is an engineering judgement this report does not "
        "make.",
        "",
    ]
    return "\n".join(lines)


def write_report(
    solution, path: str | Path, *, fields: Sequence[str] = _DEFAULT_FIELDS
) -> Path:
    """Write the Markdown summary to a file."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        report_markdown(solution, fields=fields), encoding="utf-8"
    )
    return destination


def field_to_csv(shape, name: str = "magnitude", **kwargs: Any) -> str:
    """One field as CSV, with the position of each node or element."""

    from .fields import element_centroids

    evaluated = evaluate_field(shape, name, **kwargs)
    mesh = shape.built.mesh
    unit = evaluated.unit or field_unit(name)
    header = f"id,x,y,z,{name}" + (f"_{unit}" if unit else "")

    if evaluated.per_element:
        centroids = element_centroids(mesh)
        rows = [
            (key, centroids[key], value)
            for key, value in sorted(evaluated.element_values.items())
            if key in centroids
        ]
    else:
        rows = [
            (key, mesh.nodes[key], value)
            for key, value in sorted(evaluated.node_values.items())
        ]

    body = [
        f"{key},{point[0]:.9g},{point[1]:.9g},{point[2]:.9g},{value:.9g}"
        for key, point, value in rows
    ]
    return "\n".join([header, *body])


def path_to_csv(path_result: PathResult) -> str:
    return path_result.to_csv()


def write_csv(text_or_result: Any, path: str | Path) -> Path:
    """Write CSV text, or a PathResult, to a file."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    text = (
        text_or_result.to_csv()
        if isinstance(text_or_result, PathResult)
        else str(text_or_result)
    )
    destination.write_text(text, encoding="utf-8")
    return destination


def _first_shape(solution):
    shapes = getattr(solution, "shapes", None)
    if shapes:
        return shapes[0]
    return solution
