"""Writing results out: a Markdown summary and CSV field dumps.

Both go through the headless layer, so a report is scriptable and does not
need the application open.  The report states what it was asked for and what
the solver reported; it does not editorialise about whether the answer is
acceptable, which is the engineer's call.
"""

from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field
from html import escape as html_escape
import json
from pathlib import Path
from typing import Any, Iterable, List, Mapping, Sequence

import numpy as np


from anygeometry.entities import EntityRef
from ..document import canonical_hash
from ..io.artifacts import ArtifactError, LazyResultDataset
from ..model.records import ResultQuantityDescriptor
from .extract import PathResult, probe
from .fields import evaluate_field, field_unit

__all__ = [
    "field_to_csv",
    "path_to_csv",
    "report_markdown",
    "ResultReport",
    "ResultReportContext",
    "ResultReportError",
    "build_result_report",
    "result_report_context",
    "result_report_html",
    "result_report_markdown",
    "write_csv",
    "write_report",
    "write_result_report",
]

_DEFAULT_FIELDS: tuple[str, ...] = ("magnitude", "uz", "von_mises")


def report_markdown(
    solution,
    *,
    fields: Sequence[str] = _DEFAULT_FIELDS,
    per_plate: bool = True,
) -> str:
    """A Markdown summary of one result."""

    built = solution.built
    project = built.project
    mesh = built.mesh
    shape = _first_shape(solution)

    lines: List[str] = [
        f"# {project.name}",
        "",
        f"- analysis: {getattr(shape, 'label', 'result')}",
        f"- status: {getattr(solution, 'status', 'ok')}",
        f"- nodes: {mesh.num_nodes}",
        f"- shell elements: {len(mesh.shells)}",
        f"- beam elements: {len(mesh.beams)}",
        f"- plates: {len(project.geometry.faces)}",
        f"- lines: {len(project.geometry.edges)}",
    ]
    if built.combination:
        lines.append(f"- load combination: {built.combination}")
    elif built.load_case is not None:
        lines.append(f"- load case: {built.load_case.name}")
    if project.imperfections:
        lines.append(f"- imperfections: {len(project.imperfections)}")

    lines += ["", "## Summary", "", solution.summary()]

    shapes = getattr(solution, "shapes", None)
    if shapes:
        lines += ["", "## Shapes", "", "| shape | value |", "| --- | --- |"]
        for item in shapes:
            lines.append(f"| {item.label} | {item.value:.6g} |")

    lines += ["", "## Extremes", "", "| field | unit | min | max | peak |", "| --- | --- | --- | --- | --- |"]
    for name in fields:
        try:
            evaluated = evaluate_field(shape, name)
        except (ValueError, KeyError):
            continue
        if not len(evaluated):
            continue
        low, high = evaluated.range()
        _key, peak = evaluated.extreme()
        lines.append(
            f"| {name} | {evaluated.unit or '-'} | {low:.6g} | {high:.6g} | "
            f"{peak:.6g} |"
        )

    if per_plate and project.geometry.faces:
        lines += ["", "## Per plate", "", "| plate | section | max |uz| [m] | peak von Mises [MPa] |", "| --- | --- | --- | --- |"]
        for face_id in sorted(project.geometry.faces):
            ref = EntityRef("face", face_id)
            if not mesh.nodes_on(ref):
                continue
            section = project.face_sections.get(face_id, "-")
            reading = probe(shape, ref)
            vertical = abs(reading.displacement.get("uz", 0.0))
            von_mises = reading.stresses.get("von_mises")
            stress_text = "-" if von_mises is None else f"{von_mises / 1e6:.4g}"
            lines.append(
                f"| {face_id} | {section} | {vertical:.6g} | {stress_text} |"
            )

    lines += [
        "",
        "---",
        "",
        "Generated by ANYfem. Numbers are as reported by the solver; whether "
        "they are acceptable is an engineering judgement this report does not "
        "make.",
        "",
    ]
    return "\n".join(lines)


def write_report(
    solution, path: str | Path, *, fields: Sequence[str] = _DEFAULT_FIELDS
) -> Path:
    """Write the Markdown summary to a file."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        report_markdown(solution, fields=fields), encoding="utf-8"
    )
    return destination


def field_to_csv(shape, name: str = "magnitude", **kwargs: Any) -> str:
    """One field as CSV, with the position of each node or element."""

    from .fields import element_centroids

    evaluated = evaluate_field(shape, name, **kwargs)
    mesh = shape.built.mesh
    unit = evaluated.unit or field_unit(name)
    header = f"id,x,y,z,{name}" + (f"_{unit}" if unit else "")

    if evaluated.per_element:
        centroids = element_centroids(mesh)
        rows = [
            (key, centroids[key], value)
            for key, value in sorted(evaluated.element_values.items())
            if key in centroids
        ]
    else:
        rows = [
            (key, mesh.nodes[key], value)
            for key, value in sorted(evaluated.node_values.items())
        ]

    body = [
        f"{key},{point[0]:.9g},{point[1]:.9g},{point[2]:.9g},{value:.9g}"
        for key, point, value in rows
    ]
    return "\n".join([header, *body])


def path_to_csv(path_result: PathResult) -> str:
    return path_result.to_csv()


def write_csv(text_or_result: Any, path: str | Path) -> Path:
    """Write CSV text, or a PathResult, to a file."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    text = (
        text_or_result.to_csv()
        if isinstance(text_or_result, PathResult)
        else str(text_or_result)
    )
    destination.write_text(text, encoding="utf-8")
    return destination


def _first_shape(solution):
    shapes = getattr(solution, "shapes", None)
    if shapes:
        return shapes[0]
    return solution


# ---------------------------------------------------------------------------
# Immutable artifact reporting
# ---------------------------------------------------------------------------
class ResultReportError(ValueError):
    """Raised when a retained result cannot support a truthful report."""


@dataclass(frozen=True)
class ResultReportContext:
    """Labels and hashes that accompany an immutable result artifact.

    Numerical hashes default from the sidecar.  A caller may enrich the
    context with editable labels and the *current* document hash so staleness
    is visible without changing the immutable submission provenance.
    """

    project_name: str = ""
    project_hash: str = ""
    document_id: str = ""
    document_hash: str = ""
    current_document_hash: str = ""
    mesh_id: str = ""
    model_hash: str = ""
    mesh_hash: str = ""
    analysis_id: str = ""
    analysis_name: str = ""
    analysis_type: str = ""
    analysis_hash: str = ""
    job_id: str = ""
    job_name: str = ""
    job_hash: str = ""
    job_status: str = "available"
    created_utc: str = ""
    stale: bool | None = None
    partial: bool = False
    producer_versions: Mapping[str, str] = dataclass_field(default_factory=dict)
    captured_images: tuple[str, ...] = ()


@dataclass(frozen=True)
class _Extremum:
    key: str
    component: str
    unit: str
    minimum: float | None
    maximum: float | None
    absolute_peak: float | None
    peak_frame: int | None
    finite_count: int
    nonfinite_count: int


@dataclass(frozen=True)
class _Quantity:
    descriptor: ResultQuantityDescriptor
    shape: tuple[int, ...]
    frame_count: int
    extrema: tuple[_Extremum, ...]


@dataclass(frozen=True)
class _History:
    key: str
    count: int
    x_first: float | None
    x_last: float | None
    y_minimum: float | None
    y_maximum: float | None
    nonfinite_count: int


@dataclass(frozen=True)
class _Table:
    key: str
    shape: tuple[int, ...]
    preview: Any
    truncated: bool


@dataclass(frozen=True)
class ResultReport:
    """A deterministic, renderer-independent retained-result report."""

    context: ResultReportContext
    frame_kind: str
    frames: tuple[float, ...]
    deformation_available: bool
    quantities: tuple[_Quantity, ...]
    histories: tuple[_History, ...]
    tables: tuple[_Table, ...]
    summary: Mapping[str, Any]
    diagnostics: tuple[Any, ...]
    provenance: Mapping[str, Any]

    def markdown(self) -> str:
        return _render_report_markdown(self)

    def html(self) -> str:
        return _render_report_html(self)


def result_report_context(
    dataset: LazyResultDataset,
    *,
    project: Any = None,
    job: Any = None,
    analysis: Any = None,
    current_document_hash: str = "",
    stale: bool | None = None,
    captured_images: Sequence[str | Path] = (),
) -> ResultReportContext:
    """Build report context from sidecar identity and optional project records."""

    identity = _dataset_identity(dataset)
    provenance = _metadata_mapping(dataset, "provenance")
    summary = _metadata_mapping(dataset, "summary")
    submission = provenance.get("submission", {})
    if not isinstance(submission, Mapping):
        raise ResultReportError("result submission provenance must be an object")
    hashes = provenance.get("hashes", {})
    if hashes and not isinstance(hashes, Mapping):
        raise ResultReportError("result hash provenance must be an object")
    producers = provenance.get("producer_versions", {})
    if producers and not isinstance(producers, Mapping):
        raise ResultReportError("producer_versions provenance must be an object")

    project_name = str(
        getattr(project, "name", "") or submission.get("project_name", "")
    )
    document_id = str(
        identity.get("document_id", "")
        or getattr(project, "document_id", "")
        or submission.get("document_id", "")
    )
    document_hash = str(submission.get("document_hash", ""))
    project_hash = str(submission.get("project_hash", document_hash))

    if analysis is None and project is not None and job is not None:
        analysis = getattr(project, "analyses", {}).get(
            str(getattr(job, "analysis_id", ""))
        )
    job_versions = getattr(job, "producer_versions", {}) if job is not None else {}
    merged_versions = {
        str(key): str(value)
        for key, value in dict(producers).items()
    }
    merged_versions.update(
        {str(key): str(value) for key, value in dict(job_versions or {}).items()}
    )

    model_hash = str(
        identity.get("model_hash", "")
        or hashes.get("model_hash", "")
        or getattr(job, "model_hash", "")
    )
    mesh_hash = str(
        identity.get("mesh_hash", "")
        or hashes.get("mesh_hash", "")
        or getattr(job, "mesh_hash", "")
    )
    analysis_hash = str(
        identity.get("analysis_hash", "")
        or hashes.get("analysis_hash", "")
        or getattr(job, "analysis_hash", "")
    )
    hash_payload = {
        "model_hash": model_hash,
        "mesh_hash": mesh_hash,
        "analysis_hash": analysis_hash,
    }
    job_hash = str(
        getattr(job, "input_hash", "")
        or submission.get("job_hash", "")
        or (canonical_hash(hash_payload) if all(hash_payload.values()) else "")
    )
    status = getattr(job, "status", summary.get("status", "available"))
    status = str(getattr(status, "value", status))
    partial = bool(identity.get("partial", False) or getattr(job, "partial", False))
    return ResultReportContext(
        project_name=project_name,
        project_hash=project_hash,
        document_id=document_id,
        document_hash=document_hash,
        current_document_hash=str(current_document_hash),
        mesh_id=str(identity.get("mesh_id", "")),
        model_hash=model_hash,
        mesh_hash=mesh_hash,
        analysis_id=str(getattr(analysis, "id", getattr(job, "analysis_id", ""))),
        analysis_name=str(getattr(analysis, "name", "")),
        analysis_type=str(getattr(analysis, "type", summary.get("solution_type", ""))),
        analysis_hash=analysis_hash,
        job_id=str(identity.get("artifact_id", "") or getattr(job, "id", "")),
        job_name=str(getattr(job, "name", "")),
        job_hash=job_hash,
        job_status=status,
        created_utc=str(identity.get("created_utc", "")),
        stale=stale,
        partial=partial,
        producer_versions={key: merged_versions[key] for key in sorted(merged_versions)},
        captured_images=tuple(_portable_path(value) for value in captured_images),
    )


def build_result_report(
    dataset: LazyResultDataset,
    *,
    context: ResultReportContext | None = None,
    quantities: Sequence[str] | None = None,
    frames: Sequence[int] | None = None,
    include_histories: bool = True,
    include_tables: bool = True,
    max_table_rows: int = 12,
    history_chunk_size: int = 65_536,
) -> ResultReport:
    """Inspect a retained result with at most one field frame in memory.

    ``quantities`` and ``frames`` are strict selections.  A missing quantity,
    invalid frame, malformed descriptor, inconsistent component axis, or
    unreadable dataset aborts the report instead of printing zeroes or silently
    dropping evidence.
    """

    if max_table_rows < 1:
        raise ValueError("max_table_rows must be at least one")
    if history_chunk_size < 1:
        raise ValueError("history_chunk_size must be at least one")
    try:
        dataset.validate()
        keys = tuple(dataset.field_keys)
        artifact_frames = tuple(float(value) for value in dataset.frames)
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot validate retained result: {error}") from None
    wanted = keys if quantities is None else tuple(str(value) for value in quantities)
    missing = tuple(key for key in wanted if key not in keys)
    if missing:
        raise ResultReportError(
            "retained result has no requested quantity: " + ", ".join(missing)
        )
    if len(set(wanted)) != len(wanted):
        raise ResultReportError("requested quantities must not contain duplicates")

    quantity_reports = tuple(
        _inspect_quantity(dataset, key, artifact_frames, frames)
        for key in wanted
    )
    histories = (
        tuple(
            _inspect_history(dataset, key, history_chunk_size)
            for key in dataset.history_keys
        )
        if include_histories
        else ()
    )
    tables = (
        tuple(_inspect_table(dataset, key, max_table_rows) for key in dataset.table_keys)
        if include_tables
        else ()
    )
    summary = _metadata_mapping(dataset, "summary")
    provenance = _metadata_mapping(dataset, "provenance")
    diagnostics_value = _metadata_value(dataset, "diagnostics")
    if not isinstance(diagnostics_value, Sequence) or isinstance(
        diagnostics_value, (str, bytes)
    ):
        raise ResultReportError("result diagnostics metadata must be an array")
    resolved_context = context or result_report_context(dataset)
    identity = _dataset_identity(dataset)
    return ResultReport(
        context=resolved_context,
        frame_kind=str(identity.get("frame_kind", "")),
        frames=artifact_frames,
        deformation_available="displacement" in keys,
        quantities=quantity_reports,
        histories=histories,
        tables=tables,
        summary=summary,
        diagnostics=tuple(diagnostics_value),
        provenance=provenance,
    )


def result_report_markdown(dataset: LazyResultDataset, **kwargs: Any) -> str:
    """Render a deterministic Markdown report from an HDF5 sidecar."""

    return build_result_report(dataset, **kwargs).markdown()


def result_report_html(dataset: LazyResultDataset, **kwargs: Any) -> str:
    """Render a deterministic standalone HTML report from an HDF5 sidecar."""

    return build_result_report(dataset, **kwargs).html()


def write_result_report(
    dataset: LazyResultDataset,
    path: str | Path,
    **kwargs: Any,
) -> Path:
    """Write Markdown or HTML according to ``path``'s extension."""

    destination = Path(path)
    suffix = destination.suffix.casefold()
    if suffix not in (".md", ".markdown", ".html", ".htm"):
        raise ValueError("result report path must end in .md, .markdown, .html or .htm")
    report = build_result_report(dataset, **kwargs)
    text = report.html() if suffix in (".html", ".htm") else report.markdown()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8", newline="\n")
    return destination


def _inspect_quantity(
    dataset: LazyResultDataset,
    key: str,
    artifact_frames: tuple[float, ...],
    requested_frames: Sequence[int] | None,
) -> _Quantity:
    try:
        stored = dataset.field(key)
        descriptor = stored.descriptor
        shape = tuple(int(value) for value in stored.shape)
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot inspect quantity {key!r}: {error}") from None
    if descriptor.key != key:
        raise ResultReportError(
            f"quantity {key!r} descriptor identifies {descriptor.key!r}"
        )
    if not shape or any(value < 1 for value in shape):
        raise ResultReportError(f"quantity {key!r} has empty shape {shape!r}")
    descriptor_frames = tuple(float(value) for value in descriptor.frames)
    framed = bool(descriptor_frames) or (
        bool(artifact_frames) and shape[0] == len(artifact_frames)
    )
    frame_values = descriptor_frames or (
        artifact_frames if framed else ()
    )
    frame_count = shape[0] if framed else 1
    if frame_values and len(frame_values) != frame_count:
        raise ResultReportError(
            f"quantity {key!r} has {frame_count} stored frames but "
            f"{len(frame_values)} frame descriptors"
        )
    if requested_frames is None:
        selected = tuple(range(frame_count))
    else:
        selected = tuple(int(value) for value in requested_frames)
        if len(set(selected)) != len(selected):
            raise ResultReportError("requested frames must not contain duplicates")
        invalid = tuple(value for value in selected if value < 0 or value >= frame_count)
        if invalid:
            raise ResultReportError(
                f"quantity {key!r} has no requested frame(s) "
                + ", ".join(str(value) for value in invalid)
            )
    components = tuple(descriptor.components) or ("value",)
    if descriptor.components and shape[-1] != len(descriptor.components):
        raise ResultReportError(
            f"quantity {key!r} component metadata has "
            f"{len(descriptor.components)} labels for axis length {shape[-1]}"
        )
    accumulators = [
        {
            "minimum": None,
            "maximum": None,
            "absolute_peak": None,
            "peak_frame": None,
            "finite_count": 0,
            "nonfinite_count": 0,
        }
        for _component in components
    ]
    for frame_index in selected:
        try:
            values = np.asarray(stored.read(frame_index if framed else None))
        except (OSError, KeyError, TypeError, ValueError) as error:
            raise ResultReportError(
                f"cannot read quantity {key!r} frame {frame_index}: {error}"
            ) from None
        if values.dtype.kind not in "biufc":
            raise ResultReportError(f"quantity {key!r} is not numeric")
        expected = shape[1:] if framed else shape
        if tuple(values.shape) != expected:
            raise ResultReportError(
                f"quantity {key!r} frame {frame_index} shape changed from "
                f"{expected!r} to {tuple(values.shape)!r}"
            )
        for component_index, accumulator in enumerate(accumulators):
            component_values = (
                values[..., component_index]
                if descriptor.components
                else values
            )
            flat = np.asarray(component_values).reshape(-1)
            finite = np.isfinite(flat)
            accumulator["finite_count"] += int(finite.sum())
            accumulator["nonfinite_count"] += int((~finite).sum())
            if not finite.any():
                continue
            valid = flat[finite].astype(float, copy=False)
            low = float(np.min(valid))
            high = float(np.max(valid))
            peak = float(np.max(np.abs(valid)))
            accumulator["minimum"] = (
                low
                if accumulator["minimum"] is None
                else min(float(accumulator["minimum"]), low)
            )
            accumulator["maximum"] = (
                high
                if accumulator["maximum"] is None
                else max(float(accumulator["maximum"]), high)
            )
            if accumulator["absolute_peak"] is None or peak > float(
                accumulator["absolute_peak"]
            ):
                accumulator["absolute_peak"] = peak
                accumulator["peak_frame"] = frame_index
    extrema = tuple(
        _Extremum(
            key=key,
            component=component,
            unit=descriptor.unit,
            minimum=accumulator["minimum"],
            maximum=accumulator["maximum"],
            absolute_peak=accumulator["absolute_peak"],
            peak_frame=accumulator["peak_frame"],
            finite_count=int(accumulator["finite_count"]),
            nonfinite_count=int(accumulator["nonfinite_count"]),
        )
        for component, accumulator in zip(components, accumulators)
    )
    return _Quantity(descriptor, shape, frame_count, extrema)


def _inspect_history(dataset, key: str, chunk_size: int) -> _History:
    try:
        shape = tuple(int(value) for value in dataset.history_shape(key))
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot inspect history {key!r}: {error}") from None
    if len(shape) != 1 or shape[0] < 1:
        raise ResultReportError(f"history {key!r} must be a non-empty vector")
    count = shape[0]
    x_first = x_last = y_minimum = y_maximum = None
    nonfinite = 0
    for start in range(0, count, chunk_size):
        stop = min(count, start + chunk_size)
        try:
            x_values, y_values = dataset.history(key, slice(start, stop))
        except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
            raise ResultReportError(f"cannot read history {key!r}: {error}") from None
        x_values = np.asarray(x_values, dtype=float).reshape(-1)
        y_values = np.asarray(y_values, dtype=float).reshape(-1)
        if len(x_values) != stop - start or x_values.shape != y_values.shape:
            raise ResultReportError(f"history {key!r} changed shape while reading")
        if start == 0:
            x_first = float(x_values[0])
        if stop == count:
            x_last = float(x_values[-1])
        finite_y = np.isfinite(y_values)
        nonfinite += int((~np.isfinite(x_values)).sum() + (~finite_y).sum())
        if finite_y.any():
            low = float(np.min(y_values[finite_y]))
            high = float(np.max(y_values[finite_y]))
            y_minimum = low if y_minimum is None else min(y_minimum, low)
            y_maximum = high if y_maximum is None else max(y_maximum, high)
    return _History(key, count, x_first, x_last, y_minimum, y_maximum, nonfinite)


def _inspect_table(dataset, key: str, maximum: int) -> _Table:
    try:
        shape = tuple(int(value) for value in dataset.table_shape(key))
        if not shape:
            value = dataset.table(key)
            preview = _limited_json(value, maximum)
            truncated = _value_length(value) > maximum
        else:
            row_count = shape[0]
            value = dataset.table(key, slice(0, min(row_count, maximum)))
            preview = _json_safe(value)
            truncated = row_count > maximum
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot read table {key!r}: {error}") from None
    return _Table(key, shape, preview, truncated)


def _dataset_identity(dataset) -> Mapping[str, Any]:
    try:
        value = dataset.identity
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot read result identity: {error}") from None
    if not isinstance(value, Mapping):
        raise ResultReportError("result identity must be an object")
    return value


def _metadata_value(dataset, name: str) -> Any:
    try:
        return dataset.metadata(name)
    except (ArtifactError, OSError, KeyError, TypeError, ValueError) as error:
        raise ResultReportError(f"cannot read result {name}: {error}") from None


def _metadata_mapping(dataset, name: str) -> Mapping[str, Any]:
    value = _metadata_value(dataset, name)
    if not isinstance(value, Mapping):
        raise ResultReportError(f"result {name} metadata must be an object")
    return value


def _render_report_markdown(report: ResultReport) -> str:
    context = report.context
    title = context.project_name or context.job_name or "ANYfem result"
    lines = [f"# {_md(title)} — result report", ""]
    lines += [
        "## Status",
        "",
        f"- Job status: `{_md(context.job_status or 'available')}`",
        f"- Stale against current model: `{_state(context.stale)}`",
        f"- Partial result: `{'yes' if context.partial else 'no'}`",
        f"- Deformation: `{'available' if report.deformation_available else 'unavailable'}`",
        f"- Frame axis: `{_md(report.frame_kind or 'unspecified')}` ({len(report.frames)} frame(s))",
        "",
        "## Reproducibility identity",
        "",
        "| item | value |",
        "| --- | --- |",
    ]
    for label, value in _identity_rows(context):
        lines.append(f"| {_md(label)} | `{_md(value or 'unavailable')}` |")

    lines += ["", "## Producer versions", ""]
    if context.producer_versions:
        lines += ["| producer | version |", "| --- | --- |"]
        for key in sorted(context.producer_versions):
            lines.append(
                f"| {_md(key)} | `{_md(context.producer_versions[key])}` |"
            )
    else:
        lines.append("Producer versions unavailable in this artifact.")

    lines += [
        "",
        "## Result quantities",
        "",
        "| key | label | location | shape | components | unit | basis | frames | recovery | reduction | provenance |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for quantity in report.quantities:
        descriptor = quantity.descriptor
        lines.append(
            "| "
            + " | ".join(
                _md(value)
                for value in (
                    descriptor.key,
                    descriptor.label,
                    descriptor.location,
                    _shape_text(quantity.shape),
                    ", ".join(descriptor.components) or "scalar",
                    descriptor.unit or "-",
                    descriptor.basis,
                    _frame_text(descriptor, quantity.frame_count),
                    descriptor.recovery,
                    descriptor.reduction,
                    _json_text(descriptor.provenance),
                )
            )
            + " |"
        )

    lines += [
        "",
        "## Extrema",
        "",
        "| quantity | component | unit | minimum | maximum | absolute peak | peak frame | finite | non-finite |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for quantity in report.quantities:
        for value in quantity.extrema:
            lines.append(
                f"| {_md(value.key)} | {_md(value.component)} | {_md(value.unit or '-')} | "
                f"{_number(value.minimum)} | {_number(value.maximum)} | "
                f"{_number(value.absolute_peak)} | "
                f"{'-' if value.peak_frame is None else value.peak_frame} | "
                f"{value.finite_count} | {value.nonfinite_count} |"
            )

    lines += ["", "## Histories", ""]
    if report.histories:
        lines += [
            "| key | samples | first x | last x | minimum y | maximum y | non-finite |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
        for value in report.histories:
            lines.append(
                f"| {_md(value.key)} | {value.count} | {_number(value.x_first)} | "
                f"{_number(value.x_last)} | {_number(value.y_minimum)} | "
                f"{_number(value.y_maximum)} | {value.nonfinite_count} |"
            )
    else:
        lines.append("No histories were retained.")

    lines += ["", "## Retained tables", ""]
    if report.tables:
        for table in report.tables:
            suffix = " (preview truncated)" if table.truncated else ""
            lines += [
                f"### {_md(table.key)}{suffix}",
                "",
                f"Shape: `{_shape_text(table.shape)}`",
                "",
                "```json",
                _json_text(table.preview, pretty=True),
                "```",
                "",
            ]
    else:
        lines.append("No tables were retained.")

    lines += ["", "## Solver summary", "", "```json", _json_text(report.summary, pretty=True), "```"]
    lines += ["", "## Diagnostics", ""]
    if report.diagnostics:
        lines += ["```json", _json_text(report.diagnostics, pretty=True), "```"]
    else:
        lines.append("No diagnostics were retained.")
    lines += ["", "## Provenance", "", "```json", _json_text(report.provenance, pretty=True), "```"]
    lines += ["", "## Captured views", ""]
    if context.captured_images:
        for path in context.captured_images:
            lines.append(f"- [{_md(Path(path).name or path)}]({_md_link(path)})")
    else:
        lines.append("No captured views were attached.")
    lines += [
        "",
        "---",
        "",
        "Generated by ANYfem from an immutable result artifact. Missing quantities are not interpreted as zero.",
        "",
    ]
    return "\n".join(lines)


def _render_report_html(report: ResultReport) -> str:
    context = report.context
    title = context.project_name or context.job_name or "ANYfem result"
    parts = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        f"<title>{html_escape(title)} — ANYfem result report</title>",
        "<style>body{font-family:system-ui,sans-serif;max-width:1200px;margin:2rem auto;padding:0 1rem;color:#17202a}table{border-collapse:collapse;width:100%;margin:.5rem 0 1.5rem}th,td{border:1px solid #ccd1d1;padding:.35rem .5rem;text-align:left;vertical-align:top}th{background:#eef2f3}code,pre{font-family:ui-monospace,monospace}pre{white-space:pre-wrap;background:#f5f6f7;padding:.75rem;overflow:auto}.warning{color:#922b21;font-weight:600}.ok{color:#196f3d}</style>",
        "</head>",
        "<body>",
        f"<h1>{html_escape(title)} — result report</h1>",
        "<h2>Status</h2>",
        "<ul>",
        f"<li>Job status: <code>{html_escape(context.job_status or 'available')}</code></li>",
        f"<li>Stale against current model: <code>{_state(context.stale)}</code></li>",
        f"<li>Partial result: <code>{'yes' if context.partial else 'no'}</code></li>",
        f"<li>Deformation: <code>{'available' if report.deformation_available else 'unavailable'}</code></li>",
        f"<li>Frame axis: <code>{html_escape(report.frame_kind or 'unspecified')}</code> ({len(report.frames)} frame(s))</li>",
        "</ul>",
        "<h2>Reproducibility identity</h2>",
        _html_table(("item", "value"), _identity_rows(context), code_columns=(1,)),
        "<h2>Producer versions</h2>",
    ]
    if context.producer_versions:
        parts.append(
            _html_table(
                ("producer", "version"),
                tuple((key, context.producer_versions[key]) for key in sorted(context.producer_versions)),
                code_columns=(1,),
            )
        )
    else:
        parts.append("<p>Producer versions unavailable in this artifact.</p>")
    quantity_rows = []
    for quantity in report.quantities:
        descriptor = quantity.descriptor
        quantity_rows.append(
            (
                descriptor.key,
                descriptor.label,
                descriptor.location,
                _shape_text(quantity.shape),
                ", ".join(descriptor.components) or "scalar",
                descriptor.unit or "-",
                descriptor.basis,
                _frame_text(descriptor, quantity.frame_count),
                descriptor.recovery,
                descriptor.reduction,
                _json_text(descriptor.provenance),
            )
        )
    parts += [
        "<h2>Result quantities</h2>",
        _html_table(
            ("key", "label", "location", "shape", "components", "unit", "basis", "frames", "recovery", "reduction", "provenance"),
            quantity_rows,
            code_columns=(0, 3, 4, 5, 6, 7, 8, 9, 10),
        ),
    ]
    extrema_rows = []
    for quantity in report.quantities:
        extrema_rows.extend(
            (
                value.key,
                value.component,
                value.unit or "-",
                _number(value.minimum),
                _number(value.maximum),
                _number(value.absolute_peak),
                "-" if value.peak_frame is None else str(value.peak_frame),
                str(value.finite_count),
                str(value.nonfinite_count),
            )
            for value in quantity.extrema
        )
    parts += [
        "<h2>Extrema</h2>",
        _html_table(
            ("quantity", "component", "unit", "minimum", "maximum", "absolute peak", "peak frame", "finite", "non-finite"),
            extrema_rows,
            code_columns=tuple(range(2, 9)),
        ),
        "<h2>Histories</h2>",
    ]
    if report.histories:
        parts.append(
            _html_table(
                ("key", "samples", "first x", "last x", "minimum y", "maximum y", "non-finite"),
                tuple(
                    (
                        item.key,
                        str(item.count),
                        _number(item.x_first),
                        _number(item.x_last),
                        _number(item.y_minimum),
                        _number(item.y_maximum),
                        str(item.nonfinite_count),
                    )
                    for item in report.histories
                ),
                code_columns=tuple(range(1, 7)),
            )
        )
    else:
        parts.append("<p>No histories were retained.</p>")
    parts.append("<h2>Retained tables</h2>")
    if report.tables:
        for table in report.tables:
            suffix = " (preview truncated)" if table.truncated else ""
            parts += [
                f"<h3>{html_escape(table.key + suffix)}</h3>",
                f"<p>Shape: <code>{html_escape(_shape_text(table.shape))}</code></p>",
                f"<pre>{html_escape(_json_text(table.preview, pretty=True))}</pre>",
            ]
    else:
        parts.append("<p>No tables were retained.</p>")
    parts += [
        "<h2>Solver summary</h2>",
        f"<pre>{html_escape(_json_text(report.summary, pretty=True))}</pre>",
        "<h2>Diagnostics</h2>",
        (
            f"<pre>{html_escape(_json_text(report.diagnostics, pretty=True))}</pre>"
            if report.diagnostics
            else "<p>No diagnostics were retained.</p>"
        ),
        "<h2>Provenance</h2>",
        f"<pre>{html_escape(_json_text(report.provenance, pretty=True))}</pre>",
        "<h2>Captured views</h2>",
    ]
    if context.captured_images:
        parts.append("<ul>")
        for path in context.captured_images:
            parts.append(
                f'<li><a href="{html_escape(path, quote=True)}">{html_escape(Path(path).name or path)}</a></li>'
            )
        parts.append("</ul>")
    else:
        parts.append("<p>No captured views were attached.</p>")
    parts += [
        "<hr>",
        "<p>Generated by ANYfem from an immutable result artifact. Missing quantities are not interpreted as zero.</p>",
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(parts)


def _identity_rows(context: ResultReportContext) -> tuple[tuple[str, str], ...]:
    return (
        ("project name", context.project_name),
        ("project hash", context.project_hash),
        ("document ID", context.document_id),
        ("submission document hash", context.document_hash),
        ("current document hash", context.current_document_hash),
        ("model hash", context.model_hash),
        ("mesh ID", context.mesh_id),
        ("mesh hash", context.mesh_hash),
        ("analysis ID", context.analysis_id),
        ("analysis name", context.analysis_name),
        ("analysis type", context.analysis_type),
        ("analysis hash", context.analysis_hash),
        ("job ID", context.job_id),
        ("job name", context.job_name),
        ("job hash", context.job_hash),
        ("created UTC", context.created_utc),
    )


def _html_table(headers, rows: Iterable[Sequence[Any]], *, code_columns=()) -> str:
    lines = ["<table>", "<thead><tr>"]
    lines.extend(f"<th>{html_escape(str(value))}</th>" for value in headers)
    lines += ["</tr></thead>", "<tbody>"]
    for row in rows:
        lines.append("<tr>")
        for index, value in enumerate(row):
            escaped = html_escape(str(value or "unavailable"))
            if index in code_columns:
                escaped = f"<code>{escaped}</code>"
            lines.append(f"<td>{escaped}</td>")
        lines.append("</tr>")
    lines += ["</tbody>", "</table>"]
    return "\n".join(lines)


def _frame_text(descriptor: ResultQuantityDescriptor, count: int) -> str:
    values = tuple(descriptor.frames)
    if not values:
        return str(count)
    if len(values) == 1:
        return f"1 @ {_number(values[0])}"
    return f"{len(values)} @ {_number(values[0])} … {_number(values[-1])}"


def _shape_text(shape: Sequence[int]) -> str:
    return " × ".join(str(value) for value in shape) if shape else "scalar/JSON"


def _number(value: float | None) -> str:
    return "-" if value is None else format(float(value), ".12g")


def _state(value: bool | None) -> str:
    return "unknown" if value is None else ("yes" if value else "no")


def _md(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def _md_link(value: object) -> str:
    return str(value).replace(" ", "%20").replace("(", "%28").replace(")", "%29")


def _portable_path(value: str | Path) -> str:
    return str(value).replace("\\", "/")


def _json_text(value: Any, *, pretty: bool = False) -> str:
    return json.dumps(
        _json_safe(value),
        sort_keys=True,
        ensure_ascii=False,
        allow_nan=False,
        indent=2 if pretty else None,
        separators=None if pretty else (",", ":"),
    )


def _json_safe(value: Any) -> Any:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, (float, np.floating)):
        number = float(value)
        if np.isfinite(number):
            return number
        return "NaN" if np.isnan(number) else ("Infinity" if number > 0 else "-Infinity")
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.ndarray):
        return _json_safe(value.tolist())
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return [_json_safe(item) for item in sorted(value, key=str)]
    return str(value)


def _limited_json(value: Any, maximum: int) -> Any:
    safe = _json_safe(value)
    if isinstance(safe, list):
        return safe[:maximum]
    if isinstance(safe, Mapping):
        keys = sorted(safe)[:maximum]
        return {key: safe[key] for key in keys}
    return safe


def _value_length(value: Any) -> int:
    return len(value) if isinstance(value, (Mapping, list, tuple, np.ndarray)) else 1
